// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StoreSalesAccounting.Models;

#nullable disable

namespace StoreSalesAccounting.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20220821093223_Start")]
    partial class Start
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("StoreSalesAccounting.Models.Employee", b =>
                {
                    b.Property<int>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmployeeId"), 1L, 1);

                    b.Property<int>("EmployeeCash")
                        .HasColumnType("int");

                    b.Property<DateTime>("EmployeeDay")
                        .HasColumnType("datetime2");

                    b.Property<int>("EmployeeNonCash")
                        .HasColumnType("int");

                    b.Property<int>("EmployeeOnlineCash")
                        .HasColumnType("int");

                    b.Property<int>("EmployeeTotalRevenue")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Product")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EmployeeId");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("StoreSalesAccounting.Models.StoreRevenue", b =>
                {
                    b.Property<int>("StoreRevenueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StoreRevenueId"), 1L, 1);

                    b.Property<DateTime>("Day")
                        .HasColumnType("datetime2");

                    b.Property<int>("StoreCash")
                        .HasColumnType("int");

                    b.Property<int>("StoreNonCash")
                        .HasColumnType("int");

                    b.Property<int>("StoreOnlineCash")
                        .HasColumnType("int");

                    b.Property<int>("StoreTotalRevenue")
                        .HasColumnType("int");

                    b.HasKey("StoreRevenueId");

                    b.ToTable("StoreRevenues");
                });
#pragma warning restore 612, 618
        }
    }
}
